try fix version increment, dependent on type missing

diff --git a/.github/workflows/increment-version.yml b/.github/workflows/increment-version.yml
--- a/.github/workflows/increment-version.yml
+++ b/.github/workflows/increment-version.yml
@@ -29,25 +29,36 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
+    
           node-version: '20'
+      - name: Set increment type
+        id: set-increment-type
+        run: |
+          if [ -z "${{ github.event.inputs.incrementType }}" ]; then
+            echo "Increment type is not defined. Setting to default 'patch'."
+            echo "incrementType=patch" >> $GITHUB_ENV
+          else
+            echo "incrementType=${{ github.event.inputs.incrementType }}" >> $GITHUB_ENV
+          fi
 
       - name: Increment version
         run: |
           OLD_VERSION=$(node -p "require('./package.json').version")
-          npm version ${{ github.event.inputs.incrementType }} --no-git-tag-version
+          echo "Increment Type: ${{ env.incrementType }}"
+          npm version ${{ env.incrementType }} --no-git-tag-version
           NEW_VERSION=$(node -p "require('./package.json').version")
           echo "Old version: $OLD_VERSION"
           echo "New version: $NEW_VERSION"
           
           if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
-          echo "Error: Version number has not been incremented."
-          exit 1
+            echo "Error: Version number has not been incremented."
+            exit 1
           fi
+
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add package.json
-          git status
-          git commit -m "chore(release): increment ${{ github.event.inputs.incrementType }} version from $OLD_VERSION to $NEW_VERSION" || echo "No changes to commit"
+          git commit -m "chore(release): increment ${{ env.incrementType }} version from $OLD_VERSION to $NEW_VERSION" || echo "No changes to commit"
           git push
 
       - name: Setup CHANGELOG for new version
